server:
  port: 3344
spring:
  application:
    name: microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: http://192.168.121.137/root/microservicecloud-config.git  #GitHub上面的git仓库名字